name: Check clang format

# N.B.: Runs with a read-only repo token.  Safe(ish) to check out the
# submitted branch.
on: [pull_request]

jobs:
  clang-formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'core'
        extensions: 'js'
        clangFormatVersion: 12
        style: Google

    # The Report clang format workflow (report_clang_format.yml) will
    # run (if required) after this one to post a comment to the PR.
    # (Note that the version of that workflow run will be the one on
    # the master (default) branch, not the PR target branch.)
